---

- name: Install Bareos client
  package:
    name: bareos-client
    state: present

- name: Start and enable Bareos client service
  service:
    name: "bareos-fd"
    enabled: yes
    state: started


- name: Open firewall port in default zone for Bareos client for RHEL/CentOS
  firewalld:
    port: "{{ client_port }}/tcp"
    permanent: yes
    state: enabled
  when: ansible_os_family == 'RedHat'


- name: Open firewall port in default zone for Bareos client for Debian/Ubuntu
  ufw:
    rule: allow
    port: "{{ client_port }}"
    proto: tcp
  when: ansible_os_family == 'Debian'

- name: Reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: true
  when: ansible_os_family == 'Debian'

- name: Configure clients
  template:
    src: client-bareos-dir.conf.j2
    dest: /etc/bareos/bareos-fd.d/director/bareos-dir.conf
    owner: "{{ bareos_user }}"
    group: "{{ bareos_group }}"
    mode: 0640
  notify: Restart Bareos-fd service

- name: Configure clients on Director
  template:
    src: client-fd.conf.j2
    dest: /etc/bareos/bareos-dir.d/client/{{ inventory_hostname }}-fd.conf
    owner: "{{ bareos_user }}"
    group: "{{ bareos_group }}"
    mode: 0640
  delegate_to: "{{ item }}"
  with_items: "{{ groups['director'][0] }}"
  notify: Restart Bareos-dir service
