---

- name: Install Bareos client for RHEL/CentOS 7/8
  package:
    name: bareos-client
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7

- name: Install Bareos client for RHEL/CentOS 6
  package:
    name: bareos-client-18.2*
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 6

- name: Open firewall port in default zone for Bareos client for RHEL/CentOS 7/8
  firewalld:
    port: "{{ client_port }}/tcp"
    permanent: yes
    state: enabled
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7

- name: Open firewall port in default zone for Bareos client for RHEL/CentOS 6
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ client_port }}"
    ctstate: NEW
    jump: ACCEPT
    comment: Accept connection for Bareos
  become: true
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 6

- name: Save iptables state for RHEL/CentOS 6
  community.general.iptables_state:
    state: saved
    path: /etc/sysconfig/iptables
  become: true
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 6

- name: Open firewall port in default zone for Bareos client for Debian/Ubuntu
  ufw:
    rule: allow
    port: "{{ client_port }}"
    proto: tcp
  when: ansible_os_family == 'Debian'

- name: Reload firewalld for RHEL/CentOS 7/8
  systemd:
    name: firewalld
    state: reloaded
  become: true
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7

- name: Restart iptables for RHEL/CentOS 6
  service:
    name: iptables
    enabled: yes
    state: restarted
  become: true
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 6

- name: Start and enable Bareos client service
  service:
    name: "bareos-fd"
    enabled: yes
    state: started

- name: Configure clients
  template:
    src: client-bareos-dir.conf.j2
    dest: /etc/bareos/bareos-fd.d/director/bareos-dir.conf
    owner: "{{ bareos_user }}"
    group: "{{ bareos_group }}"
    mode: 0640
  notify: Restart Bareos-fd service

- name: Configure clients on Director
  template:
    src: client-fd.conf.j2
    dest: /etc/bareos/bareos-dir.d/client/{{ inventory_hostname }}-fd.conf
    owner: "{{ bareos_user }}"
    group: "{{ bareos_group }}"
    mode: 0640
  delegate_to: "{{ item }}"
  with_items: "{{ groups['director'][0] }}"
  notify: Restart Bareos-dir service

